### ISSUE TITLE
Archive vs Aid Public

### ISSUE THREAD

**Issue by SorooshMani-NOAA** [oceanmodeling/StormEvents#9]
Does [`StormEvents`](https://github.com/oceanmodeling/StormEvents) support fetching current or last year data for storm track? I get an error trying to get info for Ida 2021.

```
>>> s = stormevents.StormEvent("Ida", 2021)
>>> s.track()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/smani/miniconda3/envs/stormevent/lib/python3.8/site-packages/stormevents/stormevent.py", line 203, in track
    track = VortexTrack.from_storm_name(
  File "/home/smani/miniconda3/envs/stormevent/lib/python3.8/site-packages/stormevents/nhc/track.py", line 135, in from_storm_name
    atcf_id = atcf_id_from_storm_name(storm_name=name, year=year)
  File "/home/smani/miniconda3/envs/stormevent/lib/python3.8/site-packages/stormevents/nhc/atcf.py", line 30, in atcf_id_from_storm_name
    return get_atcf_entry(storm_name=storm_name, year=year)[20].strip()
  File "/home/smani/miniconda3/envs/stormevent/lib/python3.8/site-packages/stormevents/nhc/atcf.py", line 82, in get_atcf_entry
    raise ValueError(
ValueError: no storms with given info ("IDA" / "NoneNone") found in year "2021"
```

I think it might be an issue of downloading from ATCF `archive` vs `aid_public` address

**Comment by zacharyburnettNOAA** [comment]
ah, good catch, I will work on a fix for this

**Comment by zacharyburnettNOAA** [comment]
fixed the problem in commit 50e0177f86a834e391b4454757cc6ce1dd724ba0

it looks like the CSV file found at https://ftp.nhc.noaa.gov/atcf/archive/storm.table is not updated with all recent storms; I changed the code to use the `nhc_storms()` function instead, which uses the latest index (at https://ftp.nhc.noaa.gov/atcf/index/storm_list.txt)

**Comment by SorooshMani-NOAA** [comment]
Using commit `ed6c9cb` I still see an issue. This time I get:
```
ftplib.error_perm: 550 atcf/archive/2021/aal092021.dat.gz: No such file or directory
```

**Comment by zacharyburnettNOAA** [comment]
ok, fixed for real this time in 0815cc634434c3b5e400dadb35ec0c9f58209322, it was assuming historical by default but the storm was too new

**Comment by zacharyburnettNOAA** [comment]
fix is going into v1.1.7
